version: "3.8"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/analytics_db
      REDIS_URL: redis://redis:6379
